/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package aulara;

import org.apache.http.HttpStatus;
import org.junit.BeforeClass;
import org.junit.Test;
import static org.junit.Assert.*;
import static io.restassured.RestAssured.*;
import static io.restassured.matcher.RestAssuredMatchers.*;
import static org.hamcrest.Matchers.*;

public class AppTest {

    @BeforeClass
    public static void preCondition(){
        baseURI = "http://localhost";
        port = 3000;
    }

    @Test
    public void getUsuarios(){
        when()
                .get("/usuarios")
        .then()
                .statusCode(HttpStatus.SC_OK);
    }

    @Test
    public void postUsuarios(){
        String userID = given()
                .body("{\n" +
                        "  \"nome\": \"Fulano da Silva\",\n" +
                        "  \"email\": \"restassure@qa.com.br\",\n" +
                        "  \"password\": \"teste\",\n" +
                        "  \"administrador\": \"true\"\n" +
                        "}")
                .contentType("application/json")
        .when()
                .post("/usuarios")
        .then()
                //.log().all()
                .statusCode(HttpStatus.SC_CREATED)
                .body("message", is("Cadastro realizado com sucesso"))
                .extract().path("_id");

    }

}
